### ISSUE TITLE
The read ECC data are all 0xFF, is this normal?

### ISSUE THREAD

**Issue by markliteng** [McMCCRU/SNANDer#12]
Hello, first of all thank you for your selflessness and hard work, so that we have such a good tool, thank you
I have encountered a problem recently. I have a router that starts normally. It uses SPI NAND and the model is MICRON MT29F2G01. It can be recognized normally with your tool. In fact, it is the only tool that can recognize this chip normally with CH341A. I used the tool you provided to read the content of this chip with -d and saved it. I found that all the contents of the ECC area read out are 0xFF. Is this normal? like this:
7F0:3C1B9FA3277B088C3C1ABFB0AF5B0280
800: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
810: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
820: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
830: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
I used this tool to read several times in a row and got the same data. All ECC data is 0xFF. In order to verify these data, I write the read data into this chip in the way of -d -v. The result The router cannot start normally, TTL display
spi check fail
Ecc cannot recovery detecte
For this reason, I bought the same router, and the ECC data read is the same. Is this chip special or the tool cannot read ECC data normally?

**Comment by McMCCRU** [comment]
Hi! It is not clear to me what you are trying to do. Your device uses a NAND controller, which uses its own mechanism of operation of the ECC and does not need the internal ECC from flash. You need to figure out how this NAND controller works, whether formatting utilities are available for it, which prepare images for flashing into a flash. You can only clone an image from flash memory using -d, but you will not be able to edit such an image.

**Comment by markliteng** [comment]
Thank you for your reply and answers, because I tried to compile some special function firmware for my device, so before doing this, I must keep a usable backup so that I can resurrect it in time when the device goes wrong, it seems I failed Up

**Comment by markliteng** [comment]
Actually, I didn't plan to edit this backup. I was just curious that the data backed up from this machine spinand can't be used on the original chip, so is the backup data useless?
