### ISSUE TITLE
Adding support for different programmers.

### ISSUE THREAD

**Issue by fifteenhex** [McMCCRU/SNANDer#14]
Hi,

I've been looking for a solution for programming SPI NAND chips for a while as flashrom can't do it.

The SoCs I'm messing around with have a weird SPI over I2C protocol and use a special USB dongle and a Windows tool. (http://linux-chenxing.org/isp/). I want to replace this with something that is open source to remove the need to have windows, use tools that are under NDA etc. flashrom already supports the SPI over I2C part for this but doesn't do SPI NAND.

Do you think it would be difficult for me to add support for using the USB dongle with this instead of the ch341a?
I took a quick look at the code and it doesn't seem like it's really tightly coupled to the ch341a but I'd like to get your opinion before I start on it.

Thanks.

**Comment by McMCCRU** [comment]
Hi! I cannot answer your question. But you can use spi_controller.c for сh341a as an example to write the commands of your SPI controller there.

**Comment by fifteenhex** [comment]
Hi,

Thanks for the information. I've created a fork and I've start my work there.
One more question: Is there a reason there is a local copy of libusb in the src?

Thanks,

Daniel

**Comment by Droid-MAX** [comment]
@fifteenhex Hi, Does your SNANDer fork support FT2232H as device to program spi flash chip or i2c eeprom？

**Comment by Droid-MAX** [comment]
@fifteenhex Can you give me some guide for that? thx
