### ISSUE TITLE
GigaDevice GD5F1GQ5UEYIG

### ISSUE THREAD

**Issue by tkso1997** [McMCCRU/SNANDer#16]
I would like to dump the content of the NAND on a router device.
Its a GigaDevice GD5F1GQ5UEYIG, could you add support for it?

[https://www.gigadevice.com/datasheet/gd5f1gq5xexxg](url)

**Comment by McMCCRU** [comment]
Hi! I added this chip, you can check. 
https://github.com/McMCCRU/SNANDer/commit/461699ef467ca7ca9e68d510fdc84790f408d684

**Comment by tkso1997** [comment]
Fantastic - thx a lot!
Will try it
