### ISSUE TITLE
Ecc error?

### ISSUE THREAD

**Issue by jacksonium** [McMCCRU/SNANDer#5]
Hi,

Thanks for publishing this great tool! I just tried to use but it received the following error.. is this normal?

SNANDer - Serial Nor/nAND/Eeprom programmeR v.1.6.1 by McMCC <mcmcc@mail.ru>

Found programmer device: WinChipHead (WCH) - CH341A
Device revision is 3.0.4
spi_nand_probe: mfr_id = 0xc2, dev_id = 0x12
Get Status Register 1: 0x00
Get Status Register 2: 0x11
Using Flash ECC.
Detected SPI NAND Flash: MXIC MX35LF1G, Flash Size: 128 MB
READ:
Read addr = 0x0000000000000000, len = 0x0000000008000000
[spinand_ecc_fail_check] : ECC cannot recover detected !, page = 0x0
spi_nand_read_page: Bad Block, ECC cannot recovery detecte, page = 0x0
Status: BAD(-1)

**Comment by jacksonium** [comment]
I tried to use the -d flag and it seems to be reading things.. not sure if it will get a correct reading so I still wonder about the above question.

Also, how long does this read supposed to take? It just kept going without any status. would be lovely if there is a status indicator. :)

**Comment by McMCCRU** [comment]
Hi!
Yes, this is normal, because the ECС considers controller of your device, it does not use the built-in algorithm in NAND flash. Use -d flag!

**Comment by McMCCRU** [comment]
The program has a progress indicator, your full amount of flash memory is considered 20 minutes...

**Comment by jacksonium** [comment]
For some reason 10 minutes only get me 20% using version 1.7. 

reading the whole 128MB flash would need something like 50 minutes. Is that normal?

**Comment by McMCCRU** [comment]
240mb read need 34 minutes
