### ISSUE TITLE
Question on status register and reading consistency

### ISSUE THREAD

**Issue by jacksonium** [McMCCRU/SNANDer#6]
I noticed the status register value would change across different read operation. Is this normal? What does it mean when register 1 = 0x38 vs 0x00, and register 2 = 0x10 vs 0x11? 

Also, i am not getting same dump across multiple read, i guess this is due to bad solder join? Should I disable screensaver? I got auto logout in the middle of the reading and wonder if it will interrupt the read by any chance?

**Comment by McMCCRU** [comment]
Please download datasheet for your chip and read his status for registers... I not have recommends for you, i don't known.
