### ISSUE TITLE
SPI NAND Flash not Detected

### ISSUE THREAD

**Issue by skxo** [McMCCRU/SNANDer#9]
Hello,

I use your SNANDer program to dump a TC58CVG2S0H, thanks for proposing such a tool based on ch341a.

During identification, I get this weird error.
```
$ ./SNANDer -i

SNANDer - Serial Nor/nAND/Eeprom programmeR v.1.7 by McMCC <mcmcc@mail.ru>

Found programmer device: WinChipHead (WCH) - CH341A
Device revision is 3.0.4
spi_nand_probe: mfr_id = 0xff, dev_id = 0x98
SPI NAND Flash Not Detected!
spi device id: ff 98 ed 51 98 (98ed5198)
SPI NOR Flash Not Detected!
```

in the datasheet, I can read:
```
Byte     | Description.                      | Value
Byte 0 | Manufacture ID (KIOXIA) | 98h
Byte 1 | Device ID.                           | CDh
```

The 98h value is present. So the 0xff are dummy bits and 0x98 is the Mfr_id.
But the device ID 0xCD is wrong (0xED instead of 0xCD)

Fyi, I tried with a MXIC and I still get 0xff as manufacturer id.

The workaround is to modify the #define value of MANUFACTURER_ID and the DEVICE_ID  to the values above (but it does not correspond to the real ID). Or to adjust the parsing of the read id command 

Any suggestion from your side, according to your previous experiments on SPI Nand?

Regards
sk

**Comment by McMCCRU** [comment]
Hi! You have some kind of hardware problem, not a software one. Either you have very long wires to the flash memory, or you are trying to read the flash memory directly from the board without removing it...

**Comment by McMCCRU** [comment]
I programmed this particular chip TC58CVG2S0H quite recently, with this software version, there were no problems.

**Comment by skxo** [comment]
Thanks Mc,  what do you recommend to use on top of the ch341a as adapter? Do you use a little adapter where you resolder the memory or do you use a ZIF socket?

**Comment by McMCCRU** [comment]
I use the adapter that came with the programmer.
![Screenshot_20210409_124910](https://user-images.githubusercontent.com/14278314/114162898-39ad3800-9932-11eb-806b-3773bf20bfe8.png)

**Comment by skxo** [comment]
from my side, I unsolder the chip and put it on a ZIF socket. this socket is then put in the ch341a and I launch the SANDer but still got this 0xff, then the 0x98.
What is your device revision of WCH ? mine is 3.0.4

**Comment by McMCCRU** [comment]
My version 3.0.4
https://github.com/McMCCRU/SNANDer/blob/main/Programmer_photos/photo3.jpg

**Comment by McMCCRU** [comment]
You set jumper in 3.3V?

**Comment by skxo** [comment]
one jumper is present on pin 1 and 2 of the top yellow pin header. Do you use different settings?

**Comment by McMCCRU** [comment]
I don’t have a power switch, I asked you because I don’t know which programmer you are using.

**Comment by Droid-MAX** [comment]
Jumper switch is used for switch mode on ch341a programmer. Short pin 1 and pin 2 is spi flash programmer, short pin 2 and pin 3 is usb2ttl mode.

**Comment by skxo** [comment]
Hi Mc,

I did few checks. 
I built a dumper with a Ftdi ft2232h and the id of the Nand is the good one. If I increase the speed of the clock, I obtain 0xFF. So I guess it is timing issues...

Do you know how to reduce the clock speed of the ch341a?
 in the spi_nand_flash.c, spi_nand_set_clock_speed() is empty.

Regards

**Comment by McMCCRU** [comment]
Hi! I have never encountered such a problem, check it with another computer or programmer. Try my advice I gave in this post - https://github.com/McMCCRU/SNANDer/issues/7#issuecomment-801021792

**Comment by ANTI443** [comment]
**McMCCRU:**

Hello I am encountering the same exact issue that you have exactly the same in every way.

I am using a ch341a programmer that I know works, I am using a wson8 adapter as shown

![image](https://user-images.githubusercontent.com/61336792/123353498-44399f80-d527-11eb-83ab-f4d5c12c9691.png)
 
what OS are you using? 

**skxo**

Do you have some sort of document you can share and help elaborate on what you did and how you did it to work thank you!

**Comment by Droid-MAX** [comment]
@ANTI443 Where can I buy that adapter？

**Comment by ANTI443** [comment]
Droid-max ebay and amazon $20 USD wson8 adapter.

https://www.ebay.com/itm/QFN8-WSON8-MLP8-MLF8-DFN8-TO-DIP8-socket-adapter-for-both-6-5MM-and-8-6MM-ICs-/324544230146?_trksid=p2349624.m46890.l49286

**Comment by Droid-MAX** [comment]
Too expensive thanks.

**Comment by Droid-MAX** [comment]
In addition, what is the service life of your adapter?

**Comment by ANTI443** [comment]
@Droid-MAX I'm not sure it's a ch341a eeprom reader what is being used here.

**Comment by ANTI443** [comment]
![20210624_212934.jpg](https://user-images.githubusercontent.com/61336792/123360747-73eea480-d533-11eb-9580-604bc6739540.jpg)

Same issue @McMCCRU I am also making sure I have 3.3v on the ch341a reader.

**Comment by McMCCRU** [comment]
https://github.com/McMCCRU/SNANDer/issues/11#issuecomment-868381791

**Comment by F5BJR** [comment]
found error etron spi not in the list
